import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="text-base-content bg-base-100">
          <Suspense fallback={<div>Loading...</div>}>
            <div className="pb-10">{children}</div>
          </Suspense>
        </div>
      </body>
    </html>
  );
}
